# -*- coding: utf-8 -*-
"""CSE317L.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WX2D2X89mhoiH_8WeRz2ySxYgnr3Mm0k

# **Class_01**
"""

x=[2,4,6,8]
for i in x:
  print (i)

fruits=["Apple","Banana"]
for i in fruits:
  print (i)

fruits=["Apple","Banana","Mango"]
for i in fruits:
  print (i)

fruits=["Apple","Banana"]
for i in fruits:
  print (i,end=".")

fruits = ["Apple", "Banana"]
for i in range(len(fruits)):
    if i < len(fruits) - 1:
        print(fruits[i], end=",")
    else:
        print(fruits[i])

fruits = ["Apple", "Banana"]
print(",".join(fruits))

fruits = ["Apple", "Banana","Mango","Coconut"]
print(",".join(fruits))

x=[2,4,6,8]
squrs = []
for i in x:
  squrs.append(i**2)
  print (squrs)

x = [2, 4, 6, 8]
squrs = []
for i in x:
    squrs.append(i**2)
print(squrs)